language: ruby
rvm:
  - 3.0.0

# If Travis writes to you too often, then disable email notifications
notifications:
  email: false

# Specifying the database
addons:
  postgresql: "12"

# Arguments for bundler
bundler_args: --without development --deployment --jobs=3 --retry=3

# We cache gems so as not to reinstall everything every time
cache: bundler

before_script:
  - sudo service postgresql stop
  - sudo service postgresql start
  # create DB
  - psql -c 'create database th_demo_test;' -U postgres
  # Copying configs
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  # Form the db structure
  - bundle exec rake db:setup
  # run PrivatePub
  - 'bundle exec rackup -s puma -E production private_pub.ru &'
  # wait, till PrivatePub initialized
  - sleep 3

script:
  - bundle exec rspec --tag ~type:feature

gemfile:
  - Gemfile
